### ISSUE TITLE
essentials.silentjoin.vanish

### ISSUE THREAD

**Issue by ISanderI** [drtshock/Essentials#37]
Currently in the Essentials config there is this setting:

.# Should players with permissions be able to join and part silently?
.# You can control this with essentials.silentjoin and essentials.silentquit permissions if it is enabled.
.# In addition, people with essentials.silentjoin.vanish will be vanished on join.
allow-silent-join-quit: true

I think this setting should be split up to something like this:
.#Allow people to join vanished with essentials.silentjoin.vanish
allow-vanish-join: false

Personally I never used this feature and everytime Im working as a OP I keep getting this unessecerry vanish on join. Im using the silent join and silent quit part.. I know I can just give myself a negative permission node for it.. But ya know.. Alt testing etc etc its just REALLY annoying.. Im sure some others would agree aswell.
And there isnt really any reason this shouldnt be added. k thx :]

**Comment by Kakifrucht** [comment]
I don't have the issue you report, without negating any permissions. 
Just set the param to false? Vanishing should be handled by VNP either way.

**Comment by zRiaz** [comment]
I dont want to set it to false because I use it for the silentjoin and silentquit.
Default as OP you get vanished when logging in if this is enabled. I would like another setting to turn off the vanish on join without having to turn off the silentjoin and silentquit.

I also said I COULD give negative perms but Im usually testing with multiple accounts etc and its just incredibly annoying being vanished everytime I log in.

**Comment by Kakifrucht** [comment]
You should install VanishNoPacket, as Essentials vanish is not safe and can easily be bypassed client side.

If anything, drtshock should consider just removing anything vanish related from Essentials, but that wouldn't be necessary imo.

**Comment by zRiaz** [comment]
I feel like you arent paying attention to what I am saying at all.

**Comment by drtshock** [comment]
I don't want to default the permissions to OP though. Most servers just don't have join/quit messages anyway.

**Comment by zRiaz** [comment]
Yea I didnt mean that, i ment that you could add a option to disable essentials.silentjoin.vanish instead of having the option to have it enabled with silentjoin & silentquit.

Because I use the silentjoin and silentquit but not the vanish. And its annoying being opped and doing testing etc and randomly be vanished all the time.

**Comment by ISanderI** [comment]
@vemacs Could this setting please be divided up into two?
I would REALLY like to disable the vanish join thing without having to disable the silent join and quit.

**Comment by drtshock** [comment]
Just revoke the permission? https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L237
