### ISSUE TITLE
Give command not dropping items on floor

### ISSUE THREAD

**Issue by HunterGPlays** [drtshock/Essentials#64]
This is more of a feature request, since the default Essentials just voids the items spawned in through the /give command with a full inventory.

Would it be possible to add a feature that could make sure it drops the items at the player's location, the same way kits are spawned when the player doesn't have space in their inventory?

**Comment by ISanderI** [comment]
I could see it being handy in some ways, but I also like being able to just fill my inventory with a item by using a random number..
Well maybe if a permission system was for this.. Because as an admin I would like to fill my inventory without dropping shit tons of items.. And as a player he would need to get any items given to him through voting rewards, donations etc..

Idk.

**Comment by HunterGPlays** [comment]
@ISanderI Maybe a config option such as "drop-given-items-if-full: true" could be added, with a permission node if necessary.

**Comment by vemacs** [comment]
https://github.com/drtshock/Essentials/commit/306aab0d8df5994ffc058dc905fb7ffe8a2f4e14
